<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mechkey"
 *
 * Auto generated by Extension Builder 2021-11-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'mechkey',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Norman Wink',
    'author_email' => '',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.3-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
