<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Nwww\\Lilly58\\' => array($typo3InstallDir . 'typo3conf/ext/lilly58/Classes'),
);
